language: generic 
sudo: requried
services:
  - docker
  
before_install:
  - docker build -t yashassamaga/docker-react  -f Dockerfile.dev .

script:
  - docker run yashassamaga/docker-react npm test run -- --coverage