language: generic 
sudo: requried
services:
  - docker
  
before_install:
  - docker build -t yashassamaga/docker-react  -f Dockerfile.dev .

script:
  - docker run yashassamaga/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-306506089118"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id:
    secure:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
